name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  BP: /home/rin/actions-runner/_work/socials-backend/socials-backend/target/debug/social-backend

jobs:
  build-backend:

    runs-on: hpgreen

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Build debug
      run: cargo update && cargo build

  notify:
    needs: build-backend
    runs-on: hpgreen

    steps:
    - name: Replace fresh bin
      run: sudo cp -f $BP /usr/bin/social-backend

    - name: Restart service
      run: sudo systemctl restart socials-backend
