name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: rpi-green

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release
