name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-backend:

    runs-on: rpi-green

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Build debug
      run: cargo build



  notify:
    needs: build-backend
    runs-on: rpi-green

    steps:
    - name: Replace fresh bin
      run: cp -f /home/rin/actions-runner/_work/socials-backend/socials-backend/target/debug/social-backend /usr/bin/social-backend

    - name: Restart service
      run: sudo systemctl restart socials-backend


