name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-backend:

    runs-on: rpi-green

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Build debug
      run: cargo build

  restart-service:
    runs-on: rpi-green

    steps:
      - name: Restart service
        run: sudo systemctl restart socials-backend
